name: Manual Build APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: |
          cd simple_live_core && flutter pub get
          cd ../simple_live_app && flutter pub get

      - name: Create Fake Properties
        # 针对 "null cannot be cast to non-null type kotlin.String" 的核心修复
        # 我们直接在 android 目录下创建一个包含 dummy 值的属性文件
        run: |
          mkdir -p simple_live_app/android
          cat <<EOF > simple_live_app/android/local.properties
          KEY_PATH=dummy
          KEY_PASSWORD=dummy
          ALIAS=dummy
          ALIAS_PASSWORD=dummy
          EOF

      - name: Build Debug APK
        run: |
          cd simple_live_app
          # 使用 debug 编译。因为有了上面的属性文件，Gradle 脚本可以读到字符串而不会崩溃
          flutter build apk --debug --no-tree-shake-icons

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-simple-live-apk
          path: simple_live_app/build/app/outputs/flutter-apk/app-debug.apk
